---
- name: Install Nginx
  apt:
    name: nginx, certbot, python3-certbot-nginx
    state: latest

- name: Copy custom error files
  copy:
    src: "{{ role_path }}/files/custom_error/"
    dest: /usr/share/nginx/error_pages
    remote_src: no
    owner: root

- name: Copy Nginx descriptor files
  copy:
    src: "{{ role_path }}/files/descriptor/"
    dest: /etc/nginx
    remote_src: no
    owner: root

- name: Restart Nginx
  service:
    name: nginx
    enabled: yes
    state: restarted  
...
