---
all:
  children:
    pve:
      children:
        tools:
          hosts:
            tools.laude.tech

    cluster-k8s-uma:
      children:
        nodo1:
          hosts: 192.168.10.191
        nodo2:
          hosts: 192.168.10.192
        nodo3:
          hosts: 192.168.10.193
        nodo4:
          hosts: 192.168.10.194      

    pro-k8s:
      hosts:
        149.202.89.13
    omnia:
      hosts: 
        208.87.129.18  
    server:
      hosts: 
        192.168.1.201  
    services:
      children:
        jenkins:
          hosts:
            172.27.1.100
        nexus:
          hosts:
            172.27.1.101
        sonar:
          hosts:
            172.27.1.102
        assets:
          hosts:
            172.27.1.103
        jenkins-agent-1:
          hosts:
            172.27.1.104
        jenkins-agent-2:
          hosts:
            172.27.1.105                       
        fsbackup:
          hosts:
            172.27.1.106
        datametrics:
          hosts:
            172.27.1.107
        nexus-blobstore-S3:
          hosts:
            172.27.1.108
        restore-sonar:
          hosts:
            172.27.1.110  
        flexric:
          hosts: 
            172.27.1.111          
        ptfr-dev:
          hosts:
            172.27.1.112
        openldap:
          hosts:
            172.27.1.113
        proxy:
          hosts:
            172.27.1.114                       
        bitwarden:
          hosts:
            172.27.1.116
        zammad:
          hosts:
            172.27.1.117
        zammad-restore:
          hosts:
            172.27.1.118             
        cats_ge:
          hosts:
            172.27.1.119            
        laudetube:
          hosts:
            172.27.1.125
        prueba1:
          hosts:
            172.27.1.200
---